name: Build layer
on: repository_dispatch
jobs:
  build:
    runs-on: ubuntu-latest 
    container:
      image: lambci/lambda:build-python3.6
    steps:
    - uses: actions/checkout@v1
    - name: build_lambda_layer_webhook
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-southeast-2
        AWS_DEFAULT_REGION: ap-southeast-2
      if: github.event.action == 'build_lambda_layer_webhook'
      run: |
        pushd scripts
        bash layer-commands.sh
        popd scripts
